### ISSUE TITLE
<wiki> Start working on this wiki project

### ISSUE THREAD

**Issue by MaksymPrymierov** [MaksymPrymierov/Conix-Core#6]
Create a wiki for the code.
Create how-to for building the project.
Create a wiki for application technology in the project.

**Comment by s-kostyuk** [comment]
In case you are interested I can recommend the Read the Docs service hosted at https://rtfd.io/. It's free to use, it supports the reStructuredText format and allows to create a very comprehensive and good-styled documentation. For example, I use Read the Docs for my Python-based everpl project: https://everpl.readthedocs.io/en/latest/. Linux kernel projects also uses RST file format and a Sphinx-based service: https://www.kernel.org/doc/html/v4.10/doc-guide/sphinx.html.

Or, maybe, the Doxygen will be a better fit for this project.
